// Generated by CoffeeScript 1.9.0
(function() {
  var citylist, getUrl, j, md5, moment, request, url, _;

  request = require('request').defaults({
    jar: true
  });

  md5 = require('MD5');

  moment = require('moment');

  _ = require('lodash');

  citylist = _.shuffle(require('./citylist').data.hotCity);

  getUrl = function(session, time, dep, arr, date) {
    var apiKey, req, sign, url;
    apiKey = '12574478';
    req = '{"searchType":"1","depCityCode":"' + dep + '","arrCityCode":"' + arr + '","leaveDate":"' + date + '","backDate":"' + date + '","itineraryFilter":"0","sellerIds":"","leaveFlightNo":"","leaveCabinClass":"0","backCabinClass":"0","utdid":"","depDate":"' + date + '"}';
    sign = md5(session + '&' + time + '&' + apiKey + '&' + req);
    return url = 'http://api.m.taobao.com/rest/h5ApiUpdate.do?api=mtop.trip.flight.flightSuperSearch&v=1.0&data=' + req + '&useNative=true&ttid=201300@travel_h5_3.1.0&appKey=12574478&t=' + time + '&sign=' + sign;
  };

  j = request.jar();

  url = getUrl();

  request.get({
    url: url,
    jar: j
  }, function(err, res, body) {
    var b, count, startTime, time, tmp, token;
    b = JSON.parse(body);
    if (b.ret[0] === 'FAIL_SYS_TOKEN_EMPTY::令牌为空') {
      tmp = j.getCookieString(url).split(';')[0].substring(9).split('_');
      token = tmp[0];
      time = tmp[1];
      count = 0;
      console.log(_.size(citylist));
      startTime = moment();
      return _.each(citylist, function(dep) {
        return _.each(citylist, function(arr) {
          if (dep === arr) {
            return;
          }
          return _.each(_.range(1, 30), function(i) {
            var date, u;
            date = moment().add(i, 'days').format('YYYY-MM-DD');
            u = getUrl(token, time, dep.code, arr.code, date);
            return request.get({
              url: u,
              jar: j
            }, function(err, res, body) {
              var speed;
              b = JSON.parse(body);
              count++;
              speed = count / moment.duration(moment(), startTime).minutes();
              return console.log(count, speed, dep.cityName, arr.cityName, date, b.ret, _.size(b.data.ow_flight));
            });
          });
        });
      });
    }
  });

}).call(this);
